#!/usr/bin/env bash
# Records the state of unfinished fixer branches in the repository, so a machine that only has the pushed branch
# (e.g. the Mac after the handoff) can finish them: merged branches get their merge commit listed, unmerged ones are
# exported as `git format-patch` series into docs/handoff/wip/<name>/.
#
#   tools/handoff/export-wip.sh [--with-uncommitted] <name>=<branch> [<name>=<branch> ...]
#
# Run it in the checkout of the integrated branch (claude/defqon-endshow-experience-wi4oos), then commit
# docs/handoff/wip/ and push. It rewrites docs/handoff/wip/STATUS.md (a table per name: merged in <sha>, or patch
# series with its commit subjects) and replaces docs/handoff/wip/<name>/ (removed when the branch is merged).
# --with-uncommitted: also saves the uncommitted tracked changes of the branch's worktree as <name>/uncommitted.diff
# (work in progress that may not even compile; untracked files are only listed).
# On the receiving side: see docs/handoff/wip/README.md.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"
WITH_UNCOMMITTED=0
[ "${1:-}" = "--with-uncommitted" ] && { WITH_UNCOMMITTED=1; shift; }
[ $# -gt 0 ] || { sed -n '2,15p' "$0"; exit 2; }
OUT=docs/handoff/wip
mkdir -p "$OUT"
HEAD_NAME="$(git rev-parse --abbrev-ref HEAD)"
HEAD_SHA="$(git rev-parse --short HEAD)"
NOW="$(date '+%Y-%m-%d %H:%M %Z')"
{
  echo "# Round status at the handoff"
  echo
  echo "Generated by \`tools/handoff/export-wip.sh\` on $NOW in the checkout of \`$HEAD_NAME\` at \`$HEAD_SHA\`."
  echo "How to use this on the Mac: [README.md](README.md)."
  echo
  echo "| Group | Branch | Status | Apply |"
  echo "|---|---|---|---|"
} > "$OUT/STATUS.md.new"
DETAILS=""
for pair in "$@"; do
  name="${pair%%=*}"
  branch="${pair#*=}"
  [ -n "$name" ] && [ "$name" != "$pair" ] || { echo "expected <name>=<branch>, got $pair" >&2; exit 2; }
  git rev-parse --verify -q "$branch^{commit}" >/dev/null || { echo "no such branch: $branch" >&2; exit 1; }
  tip="$(git rev-parse --short "$branch")"
  rm -rf "${OUT:?}/$name"
  if git merge-base --is-ancestor "$branch" HEAD; then
    merge="$(git log --merges --ancestry-path --reverse --format='%h' "$branch..HEAD" | head -1)"
    [ -n "$merge" ] || merge="$tip (fast-forward)"
    echo "| $name | \`$branch\` | merged in \`$merge\` (branch tip \`$tip\`) | nothing to do |" >> "$OUT/STATUS.md.new"
    DETAILS+=$'\n'"## $name: merged in $merge"$'\n\n'"Check on the Mac: \`git merge-base --is-ancestor $tip HEAD && echo merged\`"$'\n'
    echo "$name: merged in $merge"
    continue
  fi
  base="$(git merge-base HEAD "$branch")"
  n="$(git rev-list --count "$base..$branch")"
  mkdir -p "$OUT/$name"
  git format-patch -q -o "$OUT/$name" "$base..$branch"
  subjects="$(git log --reverse --format='- `%h` %s' "$base..$branch")"
  extra=""
  wt="$(git worktree list --porcelain | awk -v b="refs/heads/$branch" '/^worktree /{w=substr($0,10)} $0=="branch "b{print w}')"
  if [ -n "$wt" ] && [ -n "$(git -C "$wt" status --porcelain)" ]; then
    if [ "$WITH_UNCOMMITTED" = 1 ]; then
      git -C "$wt" diff HEAD > "$OUT/$name/uncommitted.diff"
      extra=" + \`uncommitted.diff\` (work in progress)"
    else
      extra=" (its worktree also had uncommitted changes that are NOT included)"
    fi
    untracked="$(git -C "$wt" ls-files --others --exclude-standard | sed 's/^/  - /')"
    [ -n "$untracked" ] && extra+=$'\n'"  untracked files in the worktree (not included):"$'\n'"$untracked"
  fi
  echo "| $name | \`$branch\` | NOT merged: $n commit(s) up to \`$tip\` exported as patches$([ -n "$extra" ] && echo ', see below') | \`git am -3 docs/handoff/wip/$name/*.patch\` |" >> "$OUT/STATUS.md.new"
  DETAILS+=$'\n'"## $name: not merged, patch series in \`docs/handoff/wip/$name/\`"$'\n\n'"Base \`$(git rev-parse --short "$base")\`, tip \`$tip\`:"$'\n'"$subjects"$'\n'
  [ -n "$extra" ] && DETAILS+=$'\n'"Note:$extra"$'\n'
  echo "$name: $n patch(es) -> $OUT/$name$extra"
done
printf '%s' "$DETAILS" >> "$OUT/STATUS.md.new"
mv "$OUT/STATUS.md.new" "$OUT/STATUS.md"
echo "wrote $OUT/STATUS.md — commit docs/handoff/wip/ and push"
