#!/usr/bin/env python3
"""Generate src/data/layout.gen.ts (anchor defaults) from research/terrain-layout.json.
Run after editing the layout research: python3 scripts/gen-layout.py"""
import json, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
d = json.loads((root / 'research/terrain-layout.json').read_text())
pa = d['pyroAnchors']; L = {g['group']: g['positions'] for g in d['lasers']}
st = d['stage']; dr = st['dragon']; wings = st['wings']
def pts(a): return [[round(float(v), 2) for v in p] for p in a]
tips = [[s['tip'][0], s['tip'][1], wings['planeZ']] for s in wings['spars']]
towers = [[t['x'], t['spireY'], t['z']] for t in st['castleCore']['towers']]
for sec in st['sideSections']:
    towers += [[t['x'], t['topY'], t['z']] for t in sec['towers']]
    c = sec['cornerTower']; towers.append([c['x'], c['topY'], c['z']])
pil = [[p['x'], p['h'], p['z']] for p in d['delayTowers']]
hp = dr['headPivot']
A = {
  'deck_front': pts(pa['deckFrontFlames']),
  'deck_back': pts([[x, 1.9, -12] for x in range(-35, 36, 5)]),
  'side_front': pts(pa['sideFrontFlames']),
  'arm_posts': pts(pa['armPostFlames']),
  'wing_left': pts([p for p in pa['wingSparFlames'] if p[0] < 0]),
  'wing_right': pts([p for p in pa['wingSparFlames'] if p[0] > 0]),
  'wing_tips': pts(tips),
  'towers_top': pts(towers),
  'tower_torches': pts(pa['towerTorches15m']),
  'corner_fireballs': pts(pa['cornerFireballs']),
  'roof': pts(pa['roofGerbs']),
  'side_rampart': pts(pa['sideRampartGerbs']),
  'roof_comets': pts(pa['roofComets']),
  'front_comets': pts(pa['frontComets']),
  'deck_gerbs': pts(pa['deckGerbs']),
  'arm_ends': pts(pa['armEndXFans']),
  'crest_comets': pts(pa['crestComets']),
  'co2': pts(pa['co2Jets']),
  'bengal': pts(pa['bengalFlares']),
  'mines': pts(pa['flashMines']),
  'hang_glitter': pts(pa['hangLineGlitter']),
  'dragon_mouth': pts([dr['mouthFlameAnchor']['position']]),
  'dragon_eyes': pts([[hp[0] - 3.4, 16.2, -8.5], [hp[0] + 3.4, 16.2, -7.8]]),
  'dragon_head': pts([[hp[0], 15.5, -10]]),
  'speaker_hangs': pts([[h['x'], 9.5, h['z']] for h in st['pa']['innerHangs'] + st['pa']['outerHangs']]),
  'dj_booth': pts([[0, 1.9, st['djPortal']['deskZ']]]),
  'pillars_top': pts(pil),
  'pillars_base': pts([[p[0], 0.45, p[2]] for p in pil]),
  'delay_towers': pts(pa['pillarCapitalFlames']),
  'foh': pts([[d['foh']['x'], 2.5, d['foh']['z']]]),
  'piano': pts(L['piano']),
  'fireworks_back': pts([[x, 4, -45] for x in range(-80, 81, 20)]),
  'fireworks_sides': pts(pa['crestComets']),
  'laser_stage': pts(L['deckFront'] + L['castleRoof'] + L['dragonFlanks'] + L['wingBases'] + L['cornerTowers']),
  'laser_field': pts(L['armEnds'] + L['pillarCapitals'] + L['piano']),
  'fixtures_truss': pts([[x, 16.5, -13] for x in range(-36, 37, 4)] + [[x, 13.5, -10] for x in list(range(-90, -39, 6)) + list(range(42, 91, 6))]),
  'fixtures_floor': pts([[x, 1.9, -1.2] for x in range(-36, 37, 3)]),
}
out = ['// GENERATED by scripts/gen-layout.py from research/terrain-layout.json — do not edit by hand.',
       '/** Design-bible default anchor positions [x, y, z] (metres, stage front z = 0, audience +Z). */',
       'export const LAYOUT_ANCHORS = {']
for k, v in A.items():
    out.append(f"  {k}: {json.dumps(v, separators=(',', ':'))},")
out.append('} as const;')
out.append('export type LayoutAnchorName = keyof typeof LAYOUT_ANCHORS;')
(root / 'src/data/layout.gen.ts').write_text('\n'.join(out) + '\n')
print('anchors:', {k: len(v) for k, v in A.items()})
